### ISSUE TITLE
To add a 'Select all' when uploading photos to Confidant Encrypted Vault

### ISSUE THREAD

**Issue by taeyonlee** [confidantstation/Confidant-APP_Android#60]
**Is your feature request related to a problem? Please describe.**
When the user tries to upload local photos in the album, he can not select all the photos at once and easily upload all to Confidant, nor back up to the Confidant node. 

**Describe the solution you'd like**
Add select all when accessing the album

**Additional context**
![IMG_0026](https://user-images.githubusercontent.com/42931121/76047115-cef63400-5f9c-11ea-9813-0e2e8d808acd.PNG)

**Comment by qlinkDev** [comment]
Thank you for your comments and Suggestions. The original intention of our design of picture backup to the app is that the user considers the important and private pictures (pictures of wallet, password, account and other information), rather than the pictures of the completely hosted user's phone. Therefore, the function of 'select all' will not be added for the time being. Thanks for your understanding.
